#pragma once

#include <set>
#include <string>
#include <vector>

using std::set, std::string, std::vector;

inline set<string> MOCK_SELECT_CLAUSE_DATA = {"a", "b", "c", "d", "e" };

inline set<string> MOCK_RESULTS_1_COL
        = { "a", "b", "c", "d", "e" };

inline set<string> MOCK_RESULTS_2_COL
        = { "a a", "a b", "a c", "a d", "a e",
            "b a", "b b", "b c", "b d", "b e",
            "c a", "c b", "c c", "c d", "c e",
            "d a", "d b", "d c", "d d", "d e",
            "e a", "e b", "e c", "e d", "e e" };

inline set<string> MOCK_ALL_COL 
        = { "a a a a", "a a a b", "a a a c", "a a a d", "a a a e", 
            "a a b a", "a a b b", "a a b c", "a a b d", "a a b e", 
            "a a c a", "a a c b", "a a c c", "a a c d", "a a c e", 
            "a a d a", "a a d b", "a a d c", "a a d d", "a a d e", 
            "a a e a", "a a e b", "a a e c", "a a e d", "a a e e", 
            "a b a a", "a b a b", "a b a c", "a b a d", "a b a e", 
            "a b b a", "a b b b", "a b b c", "a b b d", "a b b e", 
            "a b c a", "a b c b", "a b c c", "a b c d", "a b c e", 
            "a b d a", "a b d b", "a b d c", "a b d d", "a b d e", 
            "a b e a", "a b e b", "a b e c", "a b e d", "a b e e", 
            "a c a a", "a c a b", "a c a c", "a c a d", "a c a e", 
            "a c b a", "a c b b", "a c b c", "a c b d", "a c b e", 
            "a c c a", "a c c b", "a c c c", "a c c d", "a c c e", 
            "a c d a", "a c d b", "a c d c", "a c d d", "a c d e", 
            "a c e a", "a c e b", "a c e c", "a c e d", "a c e e", 
            "a d a a", "a d a b", "a d a c", "a d a d", "a d a e", 
            "a d b a", "a d b b", "a d b c", "a d b d", "a d b e", 
            "a d c a", "a d c b", "a d c c", "a d c d", "a d c e", 
            "a d d a", "a d d b", "a d d c", "a d d d", "a d d e", 
            "a d e a", "a d e b", "a d e c", "a d e d", "a d e e", 
            "a e a a", "a e a b", "a e a c", "a e a d", "a e a e", 
            "a e b a", "a e b b", "a e b c", "a e b d", "a e b e", 
            "a e c a", "a e c b", "a e c c", "a e c d", "a e c e", 
            "a e d a", "a e d b", "a e d c", "a e d d", "a e d e", 
            "a e e a", "a e e b", "a e e c", "a e e d", "a e e e", 
            "b a a a", "b a a b", "b a a c", "b a a d", "b a a e", 
            "b a b a", "b a b b", "b a b c", "b a b d", "b a b e", 
            "b a c a", "b a c b", "b a c c", "b a c d", "b a c e", 
            "b a d a", "b a d b", "b a d c", "b a d d", "b a d e", 
            "b a e a", "b a e b", "b a e c", "b a e d", "b a e e", 
            "b b a a", "b b a b", "b b a c", "b b a d", "b b a e", 
            "b b b a", "b b b b", "b b b c", "b b b d", "b b b e", 
            "b b c a", "b b c b", "b b c c", "b b c d", "b b c e", 
            "b b d a", "b b d b", "b b d c", "b b d d", "b b d e", 
            "b b e a", "b b e b", "b b e c", "b b e d", "b b e e", 
            "b c a a", "b c a b", "b c a c", "b c a d", "b c a e", 
            "b c b a", "b c b b", "b c b c", "b c b d", "b c b e", 
            "b c c a", "b c c b", "b c c c", "b c c d", "b c c e", 
            "b c d a", "b c d b", "b c d c", "b c d d", "b c d e", 
            "b c e a", "b c e b", "b c e c", "b c e d", "b c e e", 
            "b d a a", "b d a b", "b d a c", "b d a d", "b d a e", 
            "b d b a", "b d b b", "b d b c", "b d b d", "b d b e", 
            "b d c a", "b d c b", "b d c c", "b d c d", "b d c e", 
            "b d d a", "b d d b", "b d d c", "b d d d", "b d d e", 
            "b d e a", "b d e b", "b d e c", "b d e d", "b d e e", 
            "b e a a", "b e a b", "b e a c", "b e a d", "b e a e", 
            "b e b a", "b e b b", "b e b c", "b e b d", "b e b e", 
            "b e c a", "b e c b", "b e c c", "b e c d", "b e c e", 
            "b e d a", "b e d b", "b e d c", "b e d d", "b e d e", 
            "b e e a", "b e e b", "b e e c", "b e e d", "b e e e", 
            "c a a a", "c a a b", "c a a c", "c a a d", "c a a e", 
            "c a b a", "c a b b", "c a b c", "c a b d", "c a b e", 
            "c a c a", "c a c b", "c a c c", "c a c d", "c a c e", 
            "c a d a", "c a d b", "c a d c", "c a d d", "c a d e", 
            "c a e a", "c a e b", "c a e c", "c a e d", "c a e e", 
            "c b a a", "c b a b", "c b a c", "c b a d", "c b a e", 
            "c b b a", "c b b b", "c b b c", "c b b d", "c b b e", 
            "c b c a", "c b c b", "c b c c", "c b c d", "c b c e", 
            "c b d a", "c b d b", "c b d c", "c b d d", "c b d e", 
            "c b e a", "c b e b", "c b e c", "c b e d", "c b e e", 
            "c c a a", "c c a b", "c c a c", "c c a d", "c c a e", 
            "c c b a", "c c b b", "c c b c", "c c b d", "c c b e", 
            "c c c a", "c c c b", "c c c c", "c c c d", "c c c e",
            "c c d a", "c c d b", "c c d c", "c c d d", "c c d e", 
            "c c e a", "c c e b", "c c e c", "c c e d", "c c e e", 
            "c d a a", "c d a b", "c d a c", "c d a d", "c d a e", 
            "c d b a", "c d b b", "c d b c", "c d b d", "c d b e",
            "c d c a", "c d c b", "c d c c", "c d c d", "c d c e",
            "c d d a", "c d d b", "c d d c", "c d d d", "c d d e", 
            "c d e a", "c d e b", "c d e c", "c d e d", "c d e e",
            "c e a a", "c e a b", "c e a c", "c e a d", "c e a e",
            "c e b a", "c e b b", "c e b c", "c e b d", "c e b e",
            "c e c a", "c e c b", "c e c c", "c e c d", "c e c e",
            "c e d a", "c e d b", "c e d c", "c e d d", "c e d e", 
            "c e e a", "c e e b", "c e e c", "c e e d", "c e e e",
            "d a a a", "d a a b", "d a a c", "d a a d", "d a a e",
            "d a b a", "d a b b", "d a b c", "d a b d", "d a b e",
            "d a c a", "d a c b", "d a c c", "d a c d", "d a c e",
            "d a d a", "d a d b", "d a d c", "d a d d", "d a d e",
            "d a e a", "d a e b", "d a e c", "d a e d", "d a e e",
            "d b a a", "d b a b", "d b a c", "d b a d", "d b a e",
            "d b b a", "d b b b", "d b b c", "d b b d", "d b b e",
            "d b c a", "d b c b", "d b c c", "d b c d", "d b c e",
            "d b d a", "d b d b", "d b d c", "d b d d", "d b d e",
            "d b e a", "d b e b", "d b e c", "d b e d", "d b e e",
            "d c a a", "d c a b", "d c a c", "d c a d", "d c a e",
            "d c b a", "d c b b", "d c b c", "d c b d", "d c b e",
            "d c c a", "d c c b", "d c c c", "d c c d", "d c c e",
            "d c d a", "d c d b", "d c d c", "d c d d", "d c d e",
            "d c e a", "d c e b", "d c e c", "d c e d", "d c e e",
            "d d a a", "d d a b", "d d a c", "d d a d", "d d a e",
            "d d b a", "d d b b", "d d b c", "d d b d", "d d b e",
            "d d c a", "d d c b", "d d c c", "d d c d", "d d c e",
            "d d d a", "d d d b", "d d d c", "d d d d", "d d d e",
            "d d e a", "d d e b", "d d e c", "d d e d", "d d e e",
            "d e a a", "d e a b", "d e a c", "d e a d", "d e a e",
            "d e b a", "d e b b", "d e b c", "d e b d", "d e b e",
            "d e c a", "d e c b", "d e c c", "d e c d", "d e c e",
            "d e d a", "d e d b", "d e d c", "d e d d", "d e d e",
            "d e e a", "d e e b", "d e e c", "d e e d", "d e e e",
            "e a a a", "e a a b", "e a a c", "e a a d", "e a a e",
            "e a b a", "e a b b", "e a b c", "e a b d", "e a b e",
            "e a c a", "e a c b", "e a c c", "e a c d", "e a c e",
            "e a d a", "e a d b", "e a d c", "e a d d", "e a d e",
            "e a e a", "e a e b", "e a e c", "e a e d", "e a e e",
            "e b a a", "e b a b", "e b a c", "e b a d", "e b a e",
            "e b b a", "e b b b", "e b b c", "e b b d", "e b b e",
            "e b c a", "e b c b", "e b c c", "e b c d", "e b c e",
            "e b d a", "e b d b", "e b d c", "e b d d", "e b d e",
            "e b e a", "e b e b", "e b e c", "e b e d", "e b e e",
            "e c a a", "e c a b", "e c a c", "e c a d", "e c a e",
            "e c b a", "e c b b", "e c b c", "e c b d", "e c b e",
            "e c c a", "e c c b", "e c c c", "e c c d", "e c c e",
            "e c d a", "e c d b", "e c d c", "e c d d", "e c d e",
            "e c e a", "e c e b", "e c e c", "e c e d", "e c e e",
            "e d a a", "e d a b", "e d a c", "e d a d", "e d a e",
            "e d b a", "e d b b", "e d b c", "e d b d", "e d b e",
            "e d c a", "e d c b", "e d c c", "e d c d", "e d c e",
            "e d d a", "e d d b", "e d d c", "e d d d", "e d d e",
            "e d e a", "e d e b", "e d e c", "e d e d", "e d e e",
            "e e a a", "e e a b", "e e a c", "e e a d", "e e a e",
            "e e b a", "e e b b", "e e b c", "e e b d", "e e b e",
            "e e c a", "e e c b", "e e c c", "e e c d", "e e c e",
            "e e d a", "e e d b", "e e d c", "e e d d", "e e d e",
            "e e e a", "e e e b", "e e e c", "e e e d", "e e e e" };
