name: Reposense
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  reposense:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - name: Install JRE
        run: sudo apt install -y default-jre wget git

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: target

      - name: Download reposense
        run: wget -O RepoSense.jar https://github.com/reposense/RepoSense/releases/download/v2.5/RepoSense.jar

      - name: Run Reposense
        run: java -jar RepoSense.jar -r ./target

      - name: Delete Unnecessary Files
        run: rm -r ./reposense-report/target*

      - name: Upload Reposense Report
        uses: actions/upload-artifact@v3
        with:
          name: reposense-report
          path: ./reposense-report/*
          retention-days: 1
