name: Test Windows

on:
  pull_request:
  workflow_dispatch:

env:
    BUILD_TYPE: Release

jobs:
  test-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Setup Build Folder
        shell: bash
        working-directory: ./Team12/Code12
        run: cmake -E make_directory ./build

      - name: Generate CMake Project
        working-directory: ./Team12/Code12/build
        shell: bash
        run: cmake -A x64 .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      
      - name: Compile SPA
        shell: bash
        working-directory: ./Team12/Code12/build
        run: |
          cmake --build . --target unit_testing --config ${BUILD_TYPE} -j 4
          cmake --build . --target integration_testing --config ${BUILD_TYPE} -j 4
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 4

      - name: Run Unit Testing
        shell: bash
        working-directory: ./Team12/Code12/build
        run: ./src/unit_testing/${BUILD_TYPE}/unit_testing.exe

      - name: Run Integration Testing
        shell: bash
        working-directory: ./Team12/Code12/build
        run: ./src/integration_testing/${BUILD_TYPE}/integration_testing.exe

      - name: Run Auotester Testing
        shell: bash
        working-directory: ./Team12/Tests12
        run: |
          chmod +x ./auto_autotester.sh 
          ./auto_autotester.sh ../Code12/build/src/autotester/${BUILD_TYPE}/autotester.exe
        continue-on-error: true

      - name: Upload out.xml artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output-artifacts
          path: ./Team12/Tests12/output/*.xml

      - name: Cleanup Directory
        if: always()
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
